### ISSUE TITLE
Error: Uncaught TypeError: Cannot read properties of undefined after toggling amplicon plot

### ISSUE THREAD

**Issue by nhhaidee** [nhhaidee/wgscovplot#36]
Uncaught TypeError: Cannot read properties of undefined (reading '__ec_inner_19')
    at eval (model.js:603:19)
    at DataDiffer.eval [as _remove] (CustomView.js:198:169)
    at DataDiffer._executeOneToOne (DataDiffer.js:161:30)
    at DataDiffer.execute (DataDiffer.js:128:75)
    at CustomChartView.render (CustomView.js:202:8)
    at Task.progress (Chart.js:247:20)
    at Task._doProgress (task.js:193:10)
    at Task.perform (task.js:159:16)
    at eval (echarts.js:1893:24)
    at GlobalModel.eval (Global.js:668:10)

**Comment by nhhaidee** [comment]
This issue is happening intermittently with Echarts v5.3.3
